/**
 * Tests for PronounTool render behavior with different tokens.
 */
import test from "node:test";
import assert from "node:assert/strict";
import PronounTool from "../src/domain/pronounTool.js";
import PronounSet from "../src/domain/pronounSet.js";

const pronounSet = new PronounSet({
  bezeichnung: "Sie/ihr",
  nominativ: "sie",
  dativ: "ihr",
  akkusativ: "sie",
  poss1: "ihr",
  poss2: "ihre",
  poss3: "ihren",
  poss4: "ihrer",
  poss5: "ihrem",
  poss6: "ihres",
});

const tool = new PronounTool([pronounSet]);

const people = [
  {
    firstName: "Alex",
    lastName: "Miller",
    lastNameSource: "user",
    salutation: "du",
    isAutoGenerated: false,
  },
];

test("Renders pronoun markers with metadata", () => {
  const result = tool.render(
    "[Nominativ] mag [Vorname].",
    people,
    [pronounSet],
    "single",
  );
  assert.ok(result.html.includes("data-pronoun=\"Sie/ihr\""));
  assert.ok(result.html.includes("data-pronoun-form=\"Nominativ\""));
  assert.ok(result.html.includes("data-name=\"true\""));
});

test("Renders address and name variants in templates", () => {
  const result = tool.render(
    "[Bezeichnung] [Nachname] [Anrede] [Anrede/Vorname + Nachname] [Unbekannt]",
    [
      {
        firstName: "Alex",
        lastName: "Smith",
        lastNameSource: "user",
        salutation: "",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("Sie/ihr"));
  assert.ok(result.html.includes("Smith"));
  assert.ok(result.html.includes("Alex Smith"));
  assert.ok(result.html.includes("Unbekannt"));
});

test("Uses fallback person data when no people are provided", () => {
  const result = tool.render(
    "[Bezeichnung] [Vorname]",
    [],
    [pronounSet],
    "each",
  );

  assert.ok(result.html.includes("Sie/ihr"));
});

test("Flags auto-generated names and preserves incomplete tokens", () => {
  const result = tool.render(
    "[Vorname] [",
    [
      {
        firstName: "Alex",
        lastName: "Miller",
        lastNameSource: "auto",
        salutation: "",
        isAutoGenerated: true,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("data-name-source=\"auto\""));
  assert.ok(result.html.includes("["));
});

test("Renders possessive forms and full-name tokens", () => {
  const result = tool.render(
    "[Dativ] [Poss. 1] [Vorname Nachname]",
    [
      {
        firstName: "Alex",
        lastName: "Smith",
        lastNameSource: "user",
        salutation: "",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("ihr"));
  assert.ok(result.html.includes("Alex Smith"));
});

test("Falls back to nominative for unknown pronoun tokens", () => {
  const originalIsPronoun = PronounTool.isPronounToken;
  PronounTool.isPronounToken = () => true;

  const result = tool.render(
    "[Unbekannt]",
    people,
    [pronounSet],
    "single",
  );

  PronounTool.isPronounToken = originalIsPronoun;

  assert.ok(result.html.includes("Sie/ihr"));
});

test("Supports accusative forms and plus-separated full names", () => {
  const result = tool.render(
    "[Akkusativ] [Vorname + Nachname]",
    [
      {
        firstName: "Alex",
        lastName: "Smith",
        lastNameSource: "user",
        salutation: "",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("Sie"));
  assert.ok(result.html.includes("Alex Smith"));
});

test("Marks auto-generated last names in output", () => {
  const result = tool.render(
    "[Nachname]",
    [
      {
        firstName: "Alex",
        lastName: "Miller",
        lastNameSource: "auto",
        salutation: "",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.equal(result.usedAutoLastName, true);
  assert.ok(result.html.includes("data-name-source=\"auto\""));
});

test("Resolves salutation with surname", () => {
  const result = tool.render(
    "[Anrede]",
    [
      {
        firstName: "Alex",
        lastName: "Smith",
        lastNameSource: "user",
        salutation: "du",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("Du Smith"));
});

test("Resolves salutation without surname", () => {
  const result = tool.render(
    "[Anrede]",
    [
      {
        firstName: "",
        lastName: "",
        lastNameSource: "user",
        salutation: "du",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("Du"));
});

test("Renders address tokens when salutation is missing", () => {
  const result = tool.render(
    "[Anrede]",
    [
      {
        firstName: "",
        lastName: "",
        lastNameSource: "user",
        salutation: "",
        isAutoGenerated: false,
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("data-name-source=\"user\""));
});

test("Defaults missing person metadata", () => {
  const result = tool.render(
    "[Vorname] [Nachname]",
    [
      {
        firstName: "Alex",
      },
    ],
    [pronounSet],
    "single",
  );

  assert.ok(result.html.includes("Alex"));
  assert.ok(result.html.includes("data-name-source=\"user\""));
});
