/**
 * Tests for results rendering output.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { createDom, cleanupDom } from "./helpers/dom.js";
import { renderResults } from "../src/features/results/resultsView.js";
import PronounSet from "../src/domain/pronounSet.js";
import SampleTexts from "../data/SampleTexts.js";
import { RESULTS_DEFAULT_HEADING } from "../src/app/constants.js";
import { $, $$ } from "../src/app/dom.js";

const baseDom = `
  <div id="resultsOutput"></div>
`;

/**
 * Build a standard PronounSet for rendering tests.
 * @returns {PronounSet}
 */
const makePronounSet = () =>
  new PronounSet({
    bezeichnung: "Sie/ihr",
    nominativ: "sie",
    dativ: "ihr",
    akkusativ: "sie",
    poss1: "ihr",
    poss2: "ihre",
    poss3: "ihren",
    poss4: "ihrer",
    poss5: "ihrem",
    poss6: "ihres",
  });

test("Renders standard text output", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  const result = renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "du",
    textKey: "school",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  assert.ok(container.querySelector(".results-heading"));
  assert.ok(container.querySelector("p"));
  assert.ok(result.listenButton);
  assert.ok($(".results-heading", container));
  assert.equal($$("p", container).length, 1);
  cleanupDom(dom);
});

test("Renders the declension view", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  const result = renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "du",
    textKey: "declensions",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  assert.ok(container.querySelector(".declension-tables"));
  assert.equal(result.listenButton, null);
  cleanupDom(dom);
});

test("Falls back to auto-generated names when missing", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  const result = renderResults({
    resultsContainer: container,
    names: [],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "neutral",
    randomMode: "each",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  assert.equal(container.dataset.nameSourceDefault, "auto");
  assert.ok(result.selectedName);
  cleanupDom(dom);
});

test("Handles an undefined names array", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  renderResults({
    resultsContainer: container,
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "school",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  assert.equal(container.dataset.nameSourceDefault, "auto");
  cleanupDom(dom);
});

test("Uses the default heading when the text key is unknown", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "missing",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const heading = container.querySelector("h2");
  assert.ok(heading);
  cleanupDom(dom);
});

test("Uses the default heading when an entry has no title", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");
  const originalTitle = SampleTexts.school.title;
  SampleTexts.school.title = "";

  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "school",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const heading = container.querySelector("h2");
  assert.ok(heading?.textContent?.startsWith(RESULTS_DEFAULT_HEADING));

  SampleTexts.school.title = originalTitle;
  cleanupDom(dom);
});

test("Skips the pronoun suffix when no pronoun set is selected", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");

  const originalEntry = SampleTexts.tempNoPronoun;
  SampleTexts.tempNoPronoun = { title: "Temp", text: "[Vorname]" };

  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [],
    salutation: "",
    textKey: "tempNoPronoun",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const heading = container.querySelector("h2");
  assert.ok(heading?.textContent?.startsWith("Temp"));
  assert.equal(heading?.textContent?.includes("–"), false);

  if (originalEntry) {
    SampleTexts.tempNoPronoun = originalEntry;
  } else {
    delete SampleTexts.tempNoPronoun;
  }

  cleanupDom(dom);
});

test("Handles entries with missing text", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");

  const originalEntry = SampleTexts.tempNoText;
  SampleTexts.tempNoText = { title: "Temp" };

  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "user",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "tempNoText",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const paragraph = container.querySelector("p");
  assert.ok(paragraph);
  assert.equal(paragraph.textContent, "");

  if (originalEntry) {
    SampleTexts.tempNoText = originalEntry;
  } else {
    delete SampleTexts.tempNoText;
  }

  cleanupDom(dom);
});

test("Shows a notice when an auto last name is used", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");

  const originalEntry = SampleTexts.tempFallback;
  SampleTexts.tempFallback = { title: "Temp", text: "[Nachname]" };

  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      lastNameSource: "auto",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "tempFallback",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const paragraph = container.querySelector("p");
  assert.ok(paragraph?.textContent?.includes("Miller"));
  assert.ok(container.querySelector(".results-disclaimer"));

  if (originalEntry) {
    SampleTexts.tempFallback = originalEntry;
  } else {
    delete SampleTexts.tempFallback;
  }

  cleanupDom(dom);
});

test("Defaults missing last name source to user", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");

  const originalEntry = SampleTexts.tempMissingSource;
  SampleTexts.tempMissingSource = { title: "Temp", text: "[Nachname]" };

  renderResults({
    resultsContainer: container,
    names: [{
      firstName: "Alex",
      lastName: "Miller",
      isAutoGenerated: false,
    }],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "tempMissingSource",
    randomMode: "single",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const paragraph = container.querySelector("p");
  assert.ok(paragraph?.textContent?.includes("Miller"));
  assert.ok(container.innerHTML.includes("data-name-source=\"user\""));

  if (originalEntry) {
    SampleTexts.tempMissingSource = originalEntry;
  } else {
    delete SampleTexts.tempMissingSource;
  }

  cleanupDom(dom);
});

test("Uses multiple names when random mode is not single", () => {
  const dom = createDom(baseDom);
  const container = dom.window.document.querySelector("#resultsOutput");

  renderResults({
    resultsContainer: container,
    names: [
      { firstName: "Alex", lastName: "Miller", lastNameSource: "user", isAutoGenerated: false },
      { firstName: "Sam", lastName: "Stone", lastNameSource: "user", isAutoGenerated: false },
    ],
    pronounSets: [makePronounSet()],
    salutation: "",
    textKey: "school",
    randomMode: "each",
    ttsAvailable: false,
    ttsSpeaking: false,
  });

  const paragraph = container.querySelector("p");
  assert.ok(paragraph);
  cleanupDom(dom);
});
