import lastNames from "../../data/lastNames.js";
import firstNames from "../../data/firstNames.js";

/**
 * Build a stable comparison key for a name object.
 * @param {object} name
 * @returns {string}
 */
export function getNameKey(name) {
  return `${name.firstName || ""}|${name.lastName || ""}`;
}

/**
 * Parse comma-separated inputs into structured name objects.
 * @param {Array<{value: string}>} inputs
 * @returns {Array<{firstName: string, lastName: string, isAutoGenerated: boolean}>}
 */
export function parseNames(inputs) {
  const rawNames = inputs
    .flatMap((input) => input.value.split(","))
    .map((value) => value.trim())
    .filter((value) => value);

  return rawNames.map((name) => {
    const parts = name.split(/\s+/).filter((part) => part);

    if (parts.length > 1) {
      const lastName = parts.pop();
      return { firstName: parts.join(" "), lastName, isAutoGenerated: false };
    }

    return {
      firstName: parts[0],
      lastName: "",
      isAutoGenerated: false,
    };
  });
}

/**
 * Pick a random first name from the list.
 * @returns {string}
 */
function getRandomFirstName() {
  return firstNames[Math.floor(Math.random() * firstNames.length)] || "Alex";
}

/**
 * Pick a random last name from the list.
 * @returns {string}
 */
export function getRandomLastName() {
  return lastNames[Math.floor(Math.random() * lastNames.length)] || "";
}

/**
 * Create a random full name, avoiding a previous key when possible.
 * @param {string|null} excludeKey
 * @returns {{firstName: string, lastName: string, isAutoGenerated: boolean, lastNameSource: string}}
 */
export function createRandomFullName(excludeKey) {
  let attempts = 0;
  let next = null;
  do {
    const firstName = getRandomFirstName();
    const lastName = getRandomLastName();
    next = {
      firstName,
      lastName,
      isAutoGenerated: true,
      lastNameSource: "auto",
    };
    attempts += 1;
  } while (excludeKey && getNameKey(next) === excludeKey && attempts < 20);

  return next;
}

/**
 * Normalize parsed names to ensure each has a last name.
 * @param {Array<{firstName: string, lastName: string, isAutoGenerated?: boolean}>} rawNames
 * @param {{defaultNameFactory?: () => object}} [options]
 * @returns {Array<{firstName: string, lastName: string, isAutoGenerated: boolean, lastNameSource: string}>}
 */
export function normalizeNames(rawNames, options = {}) {
  const { defaultNameFactory = () => createRandomFullName(null) } = options;
  const inputNames =
    rawNames && rawNames.length > 0 ? rawNames : [defaultNameFactory()];

  return inputNames.map((person) => {
    const firstName = String(person.firstName || "").trim();
    const providedLastName = String(person.lastName || "").trim();
    const isAutoGenerated = Boolean(person.isAutoGenerated);

    if (!providedLastName) {
      return {
        firstName,
        lastName: getRandomLastName(),
        isAutoGenerated,
        lastNameSource: "auto",
      };
    }

    return {
      firstName,
      lastName: providedLastName,
      isAutoGenerated,
      lastNameSource: isAutoGenerated ? "auto" : "user",
    };
  });
}
